### PR TITLE
Fds irq fix

### PR DESCRIPTION
**Pull request by negativeExponent**

### CODE REVIEW

**Comment by zeromus** [comment]
What's the motivation for this? Like, what did it break or what were you doing when you found it?

**Comment by zeromus** [comment]
any news? did you run into trouble with it or something?

**Comment by negativeExponent** [comment]
I'll redo this PR at some point. Dunno what motivation you were looking for but seems the commit message was not enough show the intent. Despite the fds irq fix (and typo fix), it still is a problem for at least one of the 4 Irq-related problematic games on fds, other than just passing all checkmark on some irq testing rom. I'll separate the other game fix as well on a bother commit.

**Comment by zeromus** [comment]
the context about the cases passing and failing is what I was looking for. something so old and so tricky needs at least a remark about what it's fixing so people know what to check in case further fixes are needed (as indeed it seems they are)

**Comment by negativeExponent** [comment]
re-submitted a similar PR https://github.com/TASEmulators/fceux/pull/523

**Pull request closed without merging**
