### PR TITLE
Emscripten driver

### PR DESCRIPTION
**Pull request by tsone**
Hi all!

This is a PR with Emscripten/WebAssembly driver. You cay try it live [here](https://tsone.kapsi.fi/em-fceux/). I'm looking for feedback and opinions if the fork could be merged as part of FCEUX codebase?

My intent was to create a simple "emulation core" and API for use in web applications. The apps would implement their own user interface around the API. For this reason I've omitted code related to GUI, cheats, debugging, TAS, Lua scripting, screenshots and movie recording.

The driver code is under `src/drivers/em` which also contains the npm package file, a readme and an API document. The npm package is live as [em-fceux](https://www.npmjs.com/package/em-fceux). There's a minimal web application example [here](https://bitbucket.org/tsone/em-fceux-example-minimal/), and the full em-fceux site source code is [here](https://bitbucket.org/tsone/em-fceux-site/).

This PR has changes in the FCEUX core code. Notably the large switch-case for CPU opcodes was replaced with a function table. Main reason for this and other changes were in the scope of the driver, performance and binary size.

This PR is a bit rough on the edges but I'm ready and available to iron out issues, and finally to merge with upstream. Originally this work started in 2014 and the code has evolved together with Emscripten. First it was for asm.js and now for WebAssembly. So it's likely there's historical changes that are no longer needed.

Looking forward to hear your feedback!

### CODE REVIEW

**Comment by zeromus** [comment]
Sorry, I know you put a lot of work into this, but there's no way we're merging it. We have enough problems maintaining fceux as it is; we don't need to be touching stuff like this. This is the wrong emulator for your emscripten doodling. You should have used a libretro core. The good news is, the core of fceux is likely to change so little in the future that merging updates (to mappers, mainly at this point) will not be hard.

**Comment by tsone** [comment]
Thanks for the quick response. I perfectly understand.

FCEUX is perfect for Emscripten port because the codebase is very mature and slow moving. So maintaining a fork is easier. Additionally FCEUX performance, mapper support and other features are great and can be tapped in when needed.

If you ever need a NES emulator for your web app/project, try `npm install em-fceux`. Cheers.

**Comment by zeromus** [comment]
fceumm is really existing for no other reason than to have new mappers added, as far as I know. it'd be an even better choice than fceux

**Comment by tsone** [comment]
Thanks for sharing. I'm not familiar with libretro. It wasn't a thing back in 2014 when I started em-fceux.

**Comment by tsone** [comment]
Update: I built RetroArch+fceumm with Emscripten. The output is ~2 MB large wasm binary which is a lot compared to ~520 KB in em-fceux. I'll admit comparison isn't fair as em-fceux omits many features. But size really matters in web applications. So fceumm should be optimised this way. Additionally fceumm should be buildable as standalone to .wasm/.js without needing RetroArch.

fceumm also should have an npm for easy install in a web project like em-fceux has. (Ok, there's one with "fceumm" name, but it's last updated 7 years ago...) Web developers want to install components like this quickly and de-facto way is through npm (or even use unpkg).

em-fceux has all this as it's aimed for web developers. It allows quickly adding a NES emulator in a web app and creating something interesting around it. To get an idea, have a look at this great work "Real Life Punch-Out!" by Ian Charnas where you play Punch-Out! over the web camera and pose estimation: https://reallifepunchout.com/

**Pull request closed without merging**
