### PR TITLE
Debug symbol table (.nl) lookup by symbol name

### PR DESCRIPTION
**Pull request by tsone**
This is my first quick stab at this feature.

I wanted to be able to use the assembler-generated `.nl` file symbols in 6502 Debugger and Lua. (Got tired typing hex addresses.) For this, I introduced an additional `map` in the `debugSymbolTable` object. (In the process I also thought it good to clean up a bit by moving the `debugSymbolTable` code to `src/` from the GUI.)

For starters I added two use cases:
1. Allow creating breakpoints using symbol names. (I don't want to type in hex anymore!)
2. New `debugger.getsymboladdress()` Lua function. For example, could be used with `memory.registerexecute()` to count subroutine cycles at runtime without needing to write the hex after every compilation.

This should be elaborated more and I'm looking for input. Let me know your thoughts.

### CODE REVIEW

**Comment by zeromus** [comment]
fixed building on windows with 0b7960ff04677577abf77b1ef0e6531a74539ee7
can you please test this on the win32 version buildbot in some way which will make these new codepaths get covered?
if you've only checked the QT debugger tools, that's not sufficient. the old windows ones need to keep working

**Comment by zeromus** [comment]
Now that I think about it, we probably have two parallel implementations of the symbolic debugging
1. formerly QT, now in the core
2. win32 only

the lua feature you added needs to work for both of them. please make that so. We don't want to deviate the lua implementations. That puts some necessary requirements on how the symbolic debugging works: if you fetch them through lua, it must work the same regardless of qt or old windows tools.

You will find yourself driven insane if you try to merge the windows and "core" symbolic debugging facilities (and it will probably be a colossal flop)

For these reasons it may be better to completely give up and just improve whichever debugger you care more about, and nix the lua thing unless you have a good argument for it.

**Comment by tsone** [comment]
Sorry not being clear. This PR wasn't at "finished" state. But anyway I'm thankful it's merged. I'll create some follow-ups that improveme this. If you have suggestions where to add symbols, let me know. You know better the low hanging fruits.

Do you mean the Windows GUI is not using Qt? And they're not at feature parity? If so, it's fortunate I didn't touch the GUI code. And I don't have a Windows device. (Maybe I should get one.)

I don't follow exactly what you mean about Lua. But to give an example/motivation, here's snippet I use for runtime performance testing when optimising routines. The assembler generates an `.nl` file, and now Lua gets the label addresses from it, so I can very rapidly change a routine and measureme performance while running the code - kind of like a real performance profiler. I can either manually test different game situations, inputs etc. throttle or speed up emulation, or perhaps even run an automated TAS recording to automate the test (didn't try this last one though).

```lua
CycleCounter = {}
CycleCounter.__index = CycleCounter
function CycleCounter:create(name, start_addr, end_addr)
  local o = {}
  setmetatable(o, CycleCounter)
  o.name = name
  o.start = 0
  o.min = 100000
  o.max = 0
  memory.registerexecute(start_addr, function(...)
      o.start = debugger.getcyclescount()
    end)
  memory.registerexecute(end_addr, function(...)
      local d = debugger.getcyclescount() - o.start
      o.min = math.min(o.min, d)
      o.max = math.max(o.max, d)
    end)
  return o
end
function CycleCounter:format()
  return string.format("%s: %d-%d", self.name, self.min, self.max)
end

emu.speedmode("normal")

update_counter = CycleCounter:create("my main update",
    debugger.getsymboladdress(0, "my_update"),
    debugger.getsymboladdress(0, "my_update@exit")
  )

while true do
  gui.text(8, 24,  update_counter:format())
  emu.frameadvance()
end
```

**Comment by vadosnaprimer** [comment]
With how much was done for the Qt port, I do feel that the Win32 version can be considered obsolete, unless there are some missing features. Qt even has the working taseditor now!

**Comment by zeromus** [comment]
Oh, that's interesting. How about let's not even include the win32 build in the next version and see how many complaints there are?

**Comment by vadosnaprimer** [comment]
Totally down for it!

**Comment by tsone** [comment]
I see. Would be best to maintain a single GUI code.

BTW Noticed @zeromus your Visual Studio project fix... Can't cmake generate the VS project? Xcode cmake project generation seems to work fine with `-GXcode` option.

**Comment by zeromus** [comment]
we're not going to use cmake for VS. I don't care if you leave files out of the vcxproj, but if you are going to be making very many big changes in fceux you will need to check the sln.

@vadosnaprimer we discussed it and decided it wasnt quite time yet to nuke the old frontend

**Comment by tsone** [comment]
Ok, thanks for the info.

**Pull request merged**
